### ISSUE TITLE
Crash when enter tardis (load dimension) when used with OTG Biome Bundle/ (without optifine)

### ISSUE THREAD

**Issue by Boromirkane** [Spectre0987/TardisMod#312] opened 2019-08-05 22:50 UTC
Crash when enter tardis (load dimension) when used with OTG Biome Bundle. 1.12.2. I have deduced these 2 mods do not play nice together. The Dalek Mod however works with Biome Bundle. Breakdown of how I produced the bug. I creative I planted a tardis coral. It grew into a weird looking tardis. Broke the coral off around it, opened the door and entered. The dimension loaded for a split second (I saw the console) (btw I disabled the Bigger than inside feature. ) then the screen warped and it crashed. Happens every time. I used the latest version Tardis 0.1.0E Biome Bundle 1.12.2 v61 forgemultipart 2.6.1.81

Bug not caused by OPTIFINE as optifine was not present in this test. 

[crash-2019-08-05_23.38.43-client.txt](https://github.com/Spectre0987/TardisMod/files/3469630/crash-2019-08-05_23.38.43-client.txt)

**Comment by Swirtzly** [comment] 2019-08-06 10:13
Duplicate of #313

**Closed by Swirtzly** 2019-08-06 10:13 UTC
