### ISSUE TITLE
Crash when entering the tardis due to console rendering (from what I can tell)

### ISSUE THREAD

**Issue by ArminZoe** [Spectre0987/TardisMod#295] opened 2019-06-29 12:12 UTC
**Crash report:**

WARNING: coremods are present:
  Regeneration Sound Handler (Regeneration-1.12.2-1.6.6.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.211.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 6/29/19 1:06 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at micdoodle8.mods.galacticraft.core.client.render.tile.TileEntityScreenRenderer.render(TileEntityScreenRenderer.java:96)
	at micdoodle8.mods.galacticraft.core.client.render.tile.TileEntityScreenRenderer.func_192841_a(TileEntityScreenRenderer.java:16)
	at net.tardis.mod.client.worldshell.RenderWorldShell.renderWorldShell(RenderWorldShell.java:69)
	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:104)
	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:144)
	at net.tardis.mod.client.renderers.controls.RenderDoor.doRender(RenderDoor.java:80)
	at net.tardis.mod.client.renderers.controls.RenderDoor.func_76986_a(RenderDoor.java:22)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1413)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at micdoodle8.mods.galacticraft.core.client.render.tile.TileEntityScreenRenderer.render(TileEntityScreenRenderer.java:96)
	at micdoodle8.mods.galacticraft.core.client.render.tile.TileEntityScreenRenderer.func_192841_a(TileEntityScreenRenderer.java:16)
	at net.tardis.mod.client.worldshell.RenderWorldShell.renderWorldShell(RenderWorldShell.java:69)
	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:104)
	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:144)
	at net.tardis.mod.client.renderers.controls.RenderDoor.doRender(RenderDoor.java:80)
	at net.tardis.mod.client.renderers.controls.RenderDoor.func_76986_a(RenderDoor.java:22)

-- Entity being rendered --
Details:
	Entity Type: tardis:tardis_door (net.tardis.mod.common.entities.controls.ControlDoor)
	Entity ID: 249
	Entity Name: Door
	Entity's Exact location: 264.50, 128.00, 256.50
	Entity's Block location: World: (264,128,256), Chunk: (at 8,8,0 in 16,16; contains blocks 256,0,256 to 271,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.tardis.mod.client.renderers.controls.RenderDoor@167dd781
	Location: 2.35,0.00,-9.97 - World: (2,0,-10), Chunk: (at 2,0,6 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 0.0
	Delta: 0.5000043
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1413)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 14573 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.2
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 475846272 bytes (453 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 2, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                    | Signature                                |
	|:------ |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.211    | GalacticraftCore-1.12.2-4.0.2.211.jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.211    | Galacticraft-Planets-1.12.2-4.0.2.211.jar | None                                     |
	| LCHIJA | tardis              | 0.1.0D       | tardis-0.1.0D.jar                         | None                                     |
	| LCHIJA | regeneration        | 1.6.6        | Regeneration-1.12.2-1.6.6.jar             | None                                     |

	Loaded coremods (and transformers): 
Regeneration Sound Handler (Regeneration-1.12.2-1.6.6.jar)
  me.swirtzly.regeneration.asm.RegenClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.211.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.4.7' Renderer: 'Intel Iris OpenGL Engine'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.2
	OpenGL: Intel Iris OpenGL Engine GL version 2.1 INTEL-12.4.7, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz

**Comment by Swirtzly** [comment] 2019-08-08 16:27
Dupe of #313

**Closed by Swirtzly** 2019-08-08 16:27 UTC
