### ISSUE TITLE
[0.0.9B] Missing crafting recipes

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#213] opened 2019-02-25 03:16 UTC
*Mod Version:* 0.0.9B

*Other mods installed:*
- JEI
- Dalek Mod
- Mineshot
- World Edit Forge

*Description:*

The following recipes are missing from the patch update but we present in previous versions. 

- Vortex Manipulator recipe
- Dematerialization circuit recipe

**Comment by MishaPlayer** [comment] 2019-02-25 16:27
Duplicate of #209

**Closed** 2019-03-18 19:10 UTC
